'use client'

import { useEffect, useState } from 'react'
import { useRouter } from 'next/navigation'
import { getSupabaseBrowserClient } from '@/lib/supabase/client'
import { ensureUserProfile } from '@/lib/actions/auth'
import type { EmailOtpType } from '@supabase/supabase-js'

// ---------------------------------------------------------------------------
// /auth/callback — client-side page
//
// WHY this is a page, not a route handler:
//
// The PKCE code-verifier is generated by the browser Supabase client
// (createBrowserClient) and stored in browser cookies/localStorage — not
// in a server-side cookie written via Set-Cookie. A server route handler
// cannot access browser storage, so exchangeCodeForSession would always
// fail with "PKCE code verifier not found in storage".
//
// By running the exchange here (client component), the browser Supabase
// client has access to the verifier it stored when signInWithOtp was called,
// and the exchange succeeds.
// ---------------------------------------------------------------------------

type Status = 'loading' | 'success' | 'error'

interface ErrorDetail {
  reason: string
  mode: string
  msg: string
  hadVerifier: boolean
  params: string
}

export default function AuthCallbackPage() {
  const router = useRouter()
  const [status, setStatus] = useState<Status>('loading')
  const [errorDetail, setErrorDetail] = useState<ErrorDetail | null>(null)

  useEffect(() => {
    const run = async () => {
      // Read params directly from window — avoids needing Suspense for useSearchParams
      const search = new URLSearchParams(window.location.search)
      const code      = search.get('code')
      const tokenHash = search.get('token_hash')
      const type      = search.get('type') as EmailOtpType | null
      const next      = search.get('next') ?? '/'
      const paramKeys = [...search.keys()].join(', ')

      console.log('[auth/callback page] ── params ───────────────────────────')
      console.log('[auth/callback page] hasCode:', !!code)
      console.log('[auth/callback page] hasTokenHash:', !!tokenHash, '| type:', type)
      console.log('[auth/callback page] next:', next)

      const supabase = getSupabaseBrowserClient()

      let exchangeError: string | null = null
      let mode = 'unknown'

      // ── Path A: OTP / token_hash flow ─────────────────────────────────────
      if (tokenHash && type) {
        mode = 'otp'
        console.log('[auth/callback page] → verifyOtp (token_hash + type)')
        const { error } = await supabase.auth.verifyOtp({ token_hash: tokenHash, type })
        if (error) exchangeError = error.message

      // ── Path B: PKCE / code flow ───────────────────────────────────────────
      } else if (code) {
        mode = 'pkce'
        console.log('[auth/callback page] → exchangeCodeForSession (code)')
        const { error } = await supabase.auth.exchangeCodeForSession(code)
        if (error) exchangeError = error.message

      } else {
        mode = 'none'
        exchangeError = `No code or token_hash in URL. Params received: ${paramKeys || '(none)'}`
      }

      if (exchangeError) {
        console.error('[auth/callback page] exchange failed:', exchangeError, '| mode:', mode)
        setErrorDetail({
          reason: mode === 'pkce' ? 'code_failed' : mode === 'otp' ? 'otp_failed' : 'no_token',
          mode,
          msg: exchangeError,
          hadVerifier: false,
          params: paramKeys,
        })
        setStatus('error')
        return
      }

      // ── Session established ────────────────────────────────────────────────
      const { data: { user } } = await supabase.auth.getUser()
      console.log('[auth/callback page] session OK — user:', user?.id, user?.email)

      if (user) {
        // Upsert profile + membership via admin server action (bypasses RLS)
        const result = await ensureUserProfile(
          user.id,
          user.email ?? '',
          user.user_metadata ?? {}
        )
        if (!result.success) {
          console.warn('[auth/callback page] ensureUserProfile non-fatal:', result.error)
        }
      }

      console.log('[auth/callback page] redirecting to:', next)
      setStatus('success')

      // Full navigation so Next.js picks up the new session cookies
      window.location.replace(next)
    }

    run()
  }, [router])

  // ── Loading state ──────────────────────────────────────────────────────────
  if (status === 'loading' || status === 'success') {
    return (
      <div className="min-h-screen bg-background flex flex-col items-center justify-center px-8 text-center">
        <div className="animate-fade-in space-y-6">
          <p className="text-[10px] uppercase tracking-[0.5em] text-tobacco">
            Authentication
          </p>
          <div className="w-16 h-px bg-gradient-to-r from-transparent via-tobacco/30 to-transparent mx-auto" />
          <p className="text-muted-foreground text-sm">
            {status === 'success' ? 'Signed in. Taking you home…' : 'Verifying your sign-in link…'}
          </p>
        </div>
      </div>
    )
  }

  // ── Error state ────────────────────────────────────────────────────────────
  const d = errorDetail!
  return (
    <div className="min-h-screen bg-background flex flex-col items-center justify-center px-8 text-center">
      <div className="max-w-md w-full animate-fade-in">
        <p className="text-[10px] uppercase tracking-[0.5em] text-tobacco mb-8">
          Authentication
        </p>

        <h1 className="font-serif text-3xl text-cream mb-6">
          Something went wrong
        </h1>

        <div className="w-16 h-px bg-gradient-to-r from-transparent via-tobacco/30 to-transparent mx-auto mb-8" />

        <p className="text-muted-foreground leading-relaxed mb-6">
          {d.reason === 'code_failed'
            ? 'The sign-in code could not be verified. This usually means the link has already been used or expired. Please request a new one.'
            : d.reason === 'otp_failed'
            ? 'The sign-in link could not be verified. It may have expired (valid for 1 hour) or already been used (single-use only).'
            : 'No authentication token was found. The link may be incomplete.'}
        </p>

        {/* Debug panel */}
        <div className="mb-8 p-4 border border-border/20 bg-card/10 text-left space-y-1 font-mono text-[11px]">
          <p className="text-[9px] uppercase tracking-[0.3em] text-tobacco/50 mb-3">
            Technical details
          </p>
          <div className="flex gap-3">
            <span className="text-muted-foreground/50 shrink-0 w-24">reason</span>
            <span className="text-cream/70 break-all">{d.reason}</span>
          </div>
          <div className="flex gap-3">
            <span className="text-muted-foreground/50 shrink-0 w-24">mode</span>
            <span className="text-cream/70">{d.mode}</span>
          </div>
          <div className="flex gap-3">
            <span className="text-muted-foreground/50 shrink-0 w-24">supabase msg</span>
            <span className="text-red-400/80 break-all">{d.msg}</span>
          </div>
          {d.params && (
            <div className="flex gap-3">
              <span className="text-muted-foreground/50 shrink-0 w-24">url params</span>
              <span className="text-cream/50 break-all">{d.params}</span>
            </div>
          )}
        </div>

        <div className="flex flex-col gap-3 items-center">
          <button
            onClick={() => window.history.back()}
            className="inline-block px-8 py-3 border border-tobacco/40 text-tobacco hover:bg-tobacco/10 transition-all duration-500 text-sm"
          >
            Try again
          </button>
          <a
            href="/"
            className="inline-block px-8 py-3 border border-cream/20 text-cream/60 hover:bg-cream/5 transition-all duration-500 text-sm"
          >
            Return home
          </a>
        </div>
      </div>
    </div>
  )
}
